version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2019 Preview
configuration: Release
platform: x64

before_build:
  - nuget restore

build:
  verbosity: minimal

artifacts:
- path: Setup\bin\ImageViewer_Setup.exe
  name: Setup
  
deploy:
- provider: GitHub
  auth_token:
    secure: Jq17Q+XMLo6eIrSZJYpZMKf34R9SoKI1ztABotrIQKS94VSdJUOMRVUZdfXk0x4N
  artifact: Setup